version: 2.0

id: telus-colophon-app

about:
  title: telus-colophon-app
  description: Standarized project metadata to specify the components, constructs and authorship of software

contacts:
  - type: team
    name: Platform Technology & Tools TEAM
    members_uri: 'https://github.com/orgs/telus/teams/platform-technology-tools-team/members'
    repositories_uri: >-
      https://github.com/orgs/telus/teams/platform-technology-tools-team/repositories

references:
  - title: Source Code
    uri: https://github.com/telus/telus-colophon-app
  - title: Homepage
    uri: https://colophon.telus.digital

environments:
  - title: NPM Package
    uri: https://www.npmjs.com/package/@telus/colophon-app
    description: Node module
