apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: telus-colophon-app
  description: >-
    Standarized project metadata to specify the components, constructs and
    authorship of software
  tags:
    - node
  annotations:
    backstage.io/kubernetes-label-selector: app.kubernetes.io/name=telus-colophon-app
    backstage.io/techdocs-ref: dir:docs
    github.com/project-slug: telus/telus-colophon-app
  links:
    - url: https://github.com/telus/telus-colophon-app
      title: Website
      icon: web
spec:
  type: service
  lifecycle: experimental
  owner: telus
  system: digital
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: telus-colophon-app
  description: >-
    Standarized project metadata to specify the components, constructs and
    authorship of software
  tags:
    - null
    - null
    - node
  annotations:
    github.com/project-slug: telus/telus-colophon-app
  links:
    - url: https://github.com/telus/telus-colophon-app
      title: API Spec
      icon: code
    - url: https://github.com/telus/telus-colophon-app
      title: Website
      icon: web
spec:
  type: openapi
  lifecycle: experimental
  owner: digital
